name: Code Review

on:
    issues:
        types:
            - labeled
    pull_request:
        types:
            - labeled

jobs:
    review_issue:
        name: Respond to reports of a new problem
        runs-on: ubuntu-latest
        if: contains(github.event.label.name, 'ready for review')
        steps:
            - name: Run code review command
              run: |
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
                  coderabit review
=======
                  @coderabit review
>>>>>>> 51dba5e (Refactor CI workflows and update build scripts for improved efficiency)
=======
                  coderabit review
>>>>>>> 479f529 (Update .github/workflows/coderabit.yml)
=======
                  coderabit review
>>>>>>> ba8386b (Update .github/workflows/coderabit.yml)

    review_pr:
        name: Review Pull Request
        runs-on: ubuntu-latest
        if: contains(github.event.pull_request.labels.*.name, 'ready for review')
        steps:
            - name: Trigger bot review
              run: |
                  @coderabit review
